// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JfUSITC_Gr4BIb5sqhkPJy1d__tKyZE',
    appId: '1:91380265549:android:bf7b82a1bc7d40e134e204',
    messagingSenderId: '91380265549',
    projectId: 'rentit-7cfc6',
    storageBucket: 'rentit-7cfc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVfzvnPyqcYT-vFrUPQyxR5VGxb4MF7dI',
    appId: '1:91380265549:ios:c97d081fe9cec7cc34e204',
    messagingSenderId: '91380265549',
    projectId: 'rentit-7cfc6',
    storageBucket: 'rentit-7cfc6.appspot.com',
    androidClientId: '91380265549-m5e93vm931k9s82d2ajjscgqfo40446e.apps.googleusercontent.com',
    iosClientId: '91380265549-au3pdlmtlso8j08ln5dj8ijf21ktin4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentit',
  );
}
